import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import { getServerAuthSession } from "~/server/auth";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const session = await getServerAuthSession();
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body><TRPCReactProvider>
        <nav><div className="flex flex-row justify-between items-center">
            <div className="text-2xl">LNM-SNClass</div>
            <div className="flex flex-row items-center justify-center gap-2 border-4 border-transparent">
              <p className="text-center text-2xl text-black">
                {session && <span>Logged in as {session.user?.name}</span>}
              </p>
              <Link
                href={session ? "/api/auth/signout" : "/api/auth/signin"}
                className="rounded-full bg-teal-500/90 px-10 py-3 font-semibold no-underline transition hover:bg-teal-500/70 "
              >
                {session ? "Sign out" : "Sign in"}
              </Link>
            </div>
          </div></nav>
        {children}
      </TRPCReactProvider></body>
    </html>
  );
}
