version: "3"
services:
  py:
    build: .
    ports:
      - "5672:5672"
      # - "8080:8080"
    # volumes:
    #   - "./scripts: /mnt"
    #   - "./requirements.txt: /scripts/requirements.txt"
    # command: celery -A tasks worker --loglevel=INFO
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"
